### ISSUE TITLE
Changes to website layout - flashRefineSearch

### ISSUE THREAD

**Issue by jrestuccio** [jrestuccio/AnyRateFlash#14]
flashRefineSearch
1. Combine branded sites into 1 checkbox labeled "Branded"
-remove the + signs on the sites
-add all sites button
1. Add all hotels button
2. change title to "Core Competitor Hotels"
3. Change Customer Compset to "Additional market Competitors"
4. add all additional market comp hotels button
5. Data Collection method
   -change Extract report from.... to "Extract includes data from daily SmartRates report (faster)"

**Comment by kevinatown** [comment]
All tasks completed and merged except:
1. Combine branded sites into 1 checkbox labeled "Branded"
   -remove the + signs on the sites
   -add all sites button

**Comment by jrestuccio** [comment]
Everything corrected, just need to fix it so Additional Competitors is a different set of hotels. (need input from customer)

**Comment by jrestuccio** [comment]
Core Competitors are UPPER case, additional compsets are not.
Created 2 new stored procedures to handle this:
usp_GetFlashHotelsForCustomerCore
usp_GetFlashHotelsForCustomerAdd
